Programmier-AG/BeeLogger

public/js/app.js

Remove rounding of data from frontend

---

pages/index.html
public/css/app.css
public/js/app.js

* y-axis always starts with 0 now
* increased height for better readability
* moved legend to bottom for full responsiveness
**Note**: Currently, the date picking only works for the compare chart, a solution for this is WIP.

Various design fixes and enhancements

---

generate_test_data.py

- limited random floats to 2 decimal digits
- changed year for 'measured' timestamp to current year

Fix generate_test_data

---

pages/display.html
public/css/display.css
public/js/display.js

1. Added gallery tab and iframe
2. Fixed UI bug where navigation didn't take up 100% width
3. Fixed UI bug where all iframes had a margin to the left

Added gallery tab and iframe and made some UI fixes

---

.github/workflows/main.yml

Just able to keep an up-to-date version of the repo in the runner's directory.

Automatic deployment (Test)

---

pages/index.html

_(see navbar on top of page)_
Branch may be deleted after merge.

Refresh button that also wipes browser cache

---

pages/components/charts.html
pages/components/current-data.html
pages/components/footer.html
pages/components/header.html
pages/components/modals.html
pages/components/sidenav.html
pages/index.html
public/css/app.css
public/js/app.js

* New colors
* Increased line thickness for better readability
* Changed view window of weight chart (to make even small changes take effect)
* New UI elements (like a footer)
* Added badges
* Other, minor improvements
* Such as text in modals, copyright notices, credits, the about page and much more

UI, charts and static content updates

---

.gitignore
app.py
pages/components/modals.html

-fixed file transmission
-switched from starttls to ssl
-disable contact form button on submit

API post_contact fix

---

pages/components/charts.html
pages/components/sidenav.html
public/css/app.css
public/js/app.js

1. The compare chart wasn't properly centered
2. All charts (including detail charts) are the same width and have the same margins now
3. Removed unintentional margins from detail charts that were particularly unpleasant in mobile view
3. Fixed a bug where the link to the weight chart in sidenav was broken
4. Added white background color to body to prevent override if the dashboard is embedded as iframe
5. Charts are now being re-rendered automatically whenever the window gets resized, which means they are now fully responsive and do no longer require a page reload to be resized

UI fixes (mainly regarding charts)

---

.gitignore
public/css/app.css

this PR fixes an issue where the brand-logo would bug into the hamburger menu icon

fixed brand-logo position bug

---

.gitignore
pages/display.html
public/css/app.css
public/js/display.js

All detail line charts do now have the same color as their line in the compare chart has.
Also, the colors have been adjusted for better readability.
Resolves #40

Changed line colors of charts

---

pages/components/footer.html

Corrected "Wagen" to "Waagen" in 'footer.html' line 7.

Fixed typo on frontend

---

generate_test_data.py
pages/components/charts.html
public/js/app.js

This is so that the weight changes can be reviewed easier, while still being able to compare to the other data

added option for a seperate weight scale on the compare chart

---

app.py
pages/display.html
public/css/display.css
public/js/display.js

#47 implemented a modular system for configurable embedded pages.
This system just worked on the dashboard. Now it's implemented on the display as well!

Embedded pages implementation for display

---

pages/components/about-modal.html
pages/components/modals.html
pages/index.html

Fixed statistics on display

---

public/js/app.js

_&ast;cough&ast; the branch name doesn't have stupid spelling mistakes_
This should fix #71 for both the dashboard and display.

Front-End: Fix Refresh Delay on Resize (#71)

---

generate_test_data.py

- Remove hard-coded `2021` and replace with the current year (dynamic)
- Make script generate test data starting from January (not May)

Chore: Fix `generate_test_data.py`

---

app.py
example_config.py
pages/base.html
pages/components/sidenav.html
pages/display.html
pages/index.html
pages/opt-in.html

This closes #88 since the changes are in here as well somehow.

Added data privacy landing page

---

docker/docker-requirements.txt

The docker image was broken because if missing packages...

Chore: Add weather dependencies to requirements file

---

Dockerfile
app.py

Closes #98 
Closes #97 
...also added a health check endpoint.

Fixed opt-in exceptions and https redirect

---

app.py
example_config.py

If this doesn't work I'll give up...

Core: Added config for proper redirection

---

app.py

The issues with embedding into an iframe should now be fixed...finally

Core: Redirect to custom scheme/url after cookie opt-in

---

app.py

Some cross-site stupidity again...

Core: Fixed opt-in cookie not getting set in iframe
